version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  api:
    build:
      context: . # current root folder
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      # wait for postgres to be ready
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ] # using entry-point will clear the command in Dockerfile
    command: [ "/app/main" ]
