name: ci-test

on:
  push:
    branches: [main]
  pull-request:
    branches: [main]

  workflow_dispatch:
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.0
        id: go

      - name: Checkout code into Go module repository
        uses: actions/checkout@v2

      - name: Test
        run: make test
